#!/usr/bin/env bash
#
# traffic-keeper agent installer.
#
# Usage (typically generated by the panel):
#
#   curl -fsSL https://raw.githubusercontent.com/PiPi-happy/traffic-keeper/main/deploy/install.sh \
#     | bash -s -- --token tk_xxx --server https://master.example.com
#
# Downloads the latest linux agent binary from GitHub Releases, installs it to
# /usr/local/bin, writes a systemd service, and starts it. The agent performs
# its own first-run registration using --token.
#
set -euo pipefail

REPO="PiPi-happy/traffic-keeper"
INSTALL_DIR="/usr/local/bin"
STATE_DIR="/var/lib/traffic-keeper"
STATE_FILE="${STATE_DIR}/agent.state.json"
SERVICE_FILE="/etc/systemd/system/traffic-keeper-agent.service"
BINARY="${INSTALL_DIR}/traffic-keeper-agent"

TOKEN=""
SERVER=""

usage() {
	cat <<EOF
Usage: install.sh --token <token> --server <master_url>

  --token    install token shown by the panel (required, first-run only)
  --server   master base URL, e.g. https://master.example.com (required)
  -h, --help show this help
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		--token) TOKEN="${2:-}"; shift 2 ;;
		--server) SERVER="${2:-}"; shift 2 ;;
		--gh-proxy) GHPROXY="${2:-}"; shift 2 ;;
		-h | --help) usage; exit 0 ;;
		*) echo "error: unknown argument: $1" >&2; usage >&2; exit 1 ;;
	esac
done

if [[ -z "$TOKEN" ]]; then echo "error: --token is required" >&2; exit 1; fi
if [[ -z "$SERVER" ]]; then echo "error: --server is required" >&2; exit 1; fi

# --- environment checks ------------------------------------------------------
if [[ "$(id -u)" -ne 0 ]]; then
	echo "error: must run as root (use sudo)" >&2
	exit 1
fi
if [[ "$(uname -s)" != "Linux" ]]; then
	echo "error: only Linux is supported" >&2
	exit 1
fi
if ! command -v systemctl >/dev/null 2>&1; then
	echo "error: systemd not found" >&2
	exit 1
fi

case "$(uname -m)" in
	x86_64 | amd64) ARCH="amd64" ;;
	aarch64 | arm64) ARCH="arm64" ;;
	*) echo "error: unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

# --- download ----------------------------------------------------------------
# GitHub release downloads are often unreachable from CN networks; route through
# the gh-proxy.org mirror by default. Override with GHPROXY=<url> (empty = direct).
GHPROXY="${GHPROXY-https://gh-proxy.org}"
URL="https://github.com/${REPO}/releases/latest/download/traffic-keeper-agent-linux-${ARCH}"
[ -n "$GHPROXY" ] && URL="${GHPROXY}/${URL}"
echo "Downloading traffic-keeper-agent (linux/${ARCH})..."
echo "  $URL"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
if ! curl -fsSL -o "$tmp" "$URL"; then
	echo "error: download failed" >&2
	echo "  tip: try another mirror, e.g. GHPROXY=https://ghproxy.com bash install.sh ..." >&2
	exit 1
fi
install -m 0755 "$tmp" "$BINARY"
echo "Installed binary: $BINARY ($("$BINARY" --help >/dev/null 2>&1 && echo ok || echo installed))"

# --- filesystem layout -------------------------------------------------------
mkdir -p "$STATE_DIR"
chmod 0755 "$STATE_DIR"

# --- systemd service ---------------------------------------------------------
cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=Traffic Keeper Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${BINARY} run --state ${STATE_FILE}
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=10
# Hardening
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=${STATE_DIR} ${INSTALL_DIR}
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable traffic-keeper-agent >/dev/null 2>&1 || true
# Stop any old instance, add this master (same server overwrites credentials),
# then start. Re-running install.sh on a host with other masters won't clobber
# them — `add` only touches the one matching server.
systemctl stop traffic-keeper-agent >/dev/null 2>&1 || true
"${BINARY}" add --server "${SERVER}" --token "${TOKEN}" --state "${STATE_FILE}"
systemctl start traffic-keeper-agent

echo
echo "Done. traffic-keeper-agent is installed and running."
echo "  status: systemctl status traffic-keeper-agent"
echo "  logs:   journalctl -u traffic-keeper-agent -f"
